### ISSUE TITLE
Visual optimizations to autocomplete and the sidebar

### ISSUE THREAD

**Issue by phadrian** [cs2103aug2015-w15-2j/main#132]
Not the most important, but could help lend a bit more user-friendliness to the application.
1. Sidebar indicators (optional)
2. Autocomplete toggle indicator (higher priority)
3. Make the autocomplete popup a bit more visually appealing

**Comment by phadrian** [comment]
(2) is complete as of now.

**Comment by garbanzos** [comment]
Decided not to implement
